import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { Navbar } from "../components"

const Home: NextPage = () => {
	return (
		<div className='h-screen'>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Navbar />
			<main className='container mx-auto md:px-20 px-10'>
				<section className='min-h-screen flex items-center'>
					<h1 className='text-8xl font-bold md:underline underline-offset-8 decoration-primary decoration-8'>
						<span className='text-primary'>Naffy</span> Dharni
					</h1>
				</section>
			</main>
		</div>
	)
}

export default Home
